// 错误码常量
const ERROR_CODES = {
  // 用户相关错误码 (1000-1999)
  VALIDATION_ERROR: '1001',
  USERNAME_FORMAT_ERROR: '1002',
  EMAIL_FORMAT_ERROR: '1003',
  PASSWORD_FORMAT_ERROR: '1004',
  USERNAME_EXISTS: '1005',
  EMAIL_EXISTS: '1006',
  USER_NOT_FOUND: '1007',
  WRONG_PASSWORD: '1008',
  ACCOUNT_DISABLED: '1009',
  TOKEN_INVALID: '1010',
  PERMISSION_DENIED: '1011',
  AVATAR_FORMAT_ERROR: '1012',
  AVATAR_TOO_LARGE: '1013',
  RECHARGE_TYPE_INVALID: '1014',
  PAYMENT_METHOD_UNSUPPORTED: '1015',
  RECHARGE_AMOUNT_INVALID: '1016',
  PAYMENT_FAILED: '1017',
  INSUFFICIENT_BALANCE: '1018',
  ORDER_NOT_FOUND: '1019',
  ORDER_EXPIRED: '1020',

  // 图片相关错误码 (2000-2999)
  IMAGE_NOT_FOUND: '2001',
  IMAGE_DELETED: '2002',
  IMAGE_ACCESS_DENIED: '2003',
  IMAGE_DELETE_DENIED: '2004',
  IMAGE_FORMAT_UNSUPPORTED: '2005',
  IMAGE_TOO_LARGE: '2006',
  IMAGE_GENERATION_FAILED: '2007',
  IMAGE_CONVERSION_FAILED: '2008',
  PROMPT_TOO_LONG: '2009',
  PROMPT_EMPTY: '2010',
  RATIO_INVALID: '2011',
  IMAGE_TYPE_INVALID: '2012',
  TASK_NOT_FOUND: '2013',
  TASK_EXPIRED: '2014',
  TASK_CANCELLED: '2015',

  // 分类相关错误码 (3000-3999)
  CATEGORY_NOT_FOUND: '3001',
  CATEGORY_NAME_EXISTS: '3002',
  CATEGORY_NAME_FORMAT_ERROR: '3003',

  // 举报相关错误码 (4000-4999)
  REPORT_CONTENT_EMPTY: '4001',
  DUPLICATE_REPORT: '4002',
  REPORT_CONTENT_TOO_LONG: '4003',
  REPORT_RATE_LIMIT: '4004',
  REPORT_NOT_FOUND: '4005',

  // 系统相关错误码 (9000-9999)
  INTERNAL_SERVER_ERROR: '9001',
  DATABASE_CONNECTION_FAILED: '9002',
  EXTERNAL_SERVICE_UNAVAILABLE: '9003',
  RATE_LIMIT_EXCEEDED: '9004',
  SERVICE_MAINTENANCE: '9005'
};

// 用户类型
const USER_TYPES = {
  FREE: 'free',
  LITE: 'lite',
  PRO: 'pro'
};

// 图片类型
const IMAGE_TYPES = {
  TEXT2IMAGE: 'text2image',
  IMAGE2IMAGE: 'image2image'
};

// 图片比例
const IMAGE_RATIOS = {
  SQUARE: '1:1',
  PORTRAIT: '3:4',
  LANDSCAPE: '4:3'
};

// 任务状态
const TASK_STATUS = {
  PENDING: 'pending',
  PROCESSING: 'processing',
  COMPLETED: 'completed',
  FAILED: 'failed',
  CANCELLED: 'cancelled'
};

// 订单状态
const ORDER_STATUS = {
  PENDING: 'pending',
  COMPLETED: 'completed',
  FAILED: 'failed',
  CANCELLED: 'cancelled'
};

// 支付方式
const PAYMENT_TYPES = {
  MASTER: 'master',
  VISA: 'visa',
  AMERICAN_EXPRESS: 'americanexpress',
  APPLE_PAY: 'applepay',
  UNION_PAY: 'unionpay'
};

// 充值类型
const RECHARGE_TYPES = {
  MONTHLY: 'monthly',
  YEARLY: 'yearly',
  CREDITS: 'credits'
};

// 文件上传限制
const UPLOAD_LIMITS = {
  AVATAR_MAX_SIZE: 5 * 1024 * 1024, // 5MB
  IMAGE_MAX_SIZE: 10 * 1024 * 1024, // 10MB
  ALLOWED_IMAGE_TYPES: ['image/jpeg', 'image/png', 'image/gif', 'image/webp'],
  ALLOWED_AVATAR_TYPES: ['image/jpeg', 'image/png']
};

module.exports = {
  ERROR_CODES,
  USER_TYPES,
  IMAGE_TYPES,
  IMAGE_RATIOS,
  TASK_STATUS,
  ORDER_STATUS,
  PAYMENT_TYPES,
  RECHARGE_TYPES,
  UPLOAD_LIMITS
}; 